### ISSUE TITLE
Lastest tag references unknown revision in go.mod file

### ISSUE THREAD

**Issue by juburr** [twpayne/go-kml#35]
Can you create a new tag of this package?

The most recent version references a commit in go-waypoint that no longer seems to exist?

> go: github.com/twpayne/go-kml/v3@upgrade (v3.1.0) requires github.com/twpayne/go-waypoint@v0.0.0-20200822110510-4f8e6bfac4df: github.com/twpayne/go-waypoint@v0.0.0-20200822110510-4f8e6bfac4df: invalid version: unknown revision 4f8e6bfac4df

v3.1.0:
https://github.com/twpayne/go-kml/blob/0069e35906799d7e17d638a5548f30190aff2756/go.mod#L9

master:
https://github.com/twpayne/go-kml/blob/c84e26de3036deda2589104c95f73456b0f76dd2/go.mod#L9

**Comment by twpayne** [comment]
OK, I've tagged https://github.com/twpayne/go-kml/releases/tag/v3.1.1 which includes updates to project infrastructure. Note that there are no user-visible changes, which is why I had not tagged a new version previously.

**Comment by juburr** [comment]
Thank you, @twpayne!
